#!/usr/bin/env python3
"""Generates resources/quests_cfg/ham.cfg: galene QuestSystem format, one chapter per level.

Level 1 uses the plain fact names (rules.*, shack.*, qso.*, goal.*), level N>1 prefixes them
with "lN." (for example "l2.shack.psu"). Quest ids: rules, shack, qso, morse for level 1 and
rules2, shack2 ... for level 2. Run: python3 tools/build_quests.py
"""
import json, os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
PARTS = [("psu", "Power supply"), ("antenna", "Antenna"), ("transceiver", "Transceiver"), ("mic", "Microphone"),
         ("speaker", "Speaker"), ("swr", "SWR meter"), ("key", "Morse key"), ("logbook", "Logbook")]
MORSE_CAP = {1: 3, 2: 6, 3: 10}
LEVELS = 3


def cond(key, op, value):
    return json.dumps([{"key": key, "op": op, "value": value}])


def q(s: str) -> str:
    return '"%s"' % s.replace("\\", "\\\\").replace('"', '\\"')


def quest(out, qid, chapter, name, desc, complete_fact):
    out += ["[quest.%s]" % qid, "chapter = %s" % q(chapter), 'type = "main"', "display_name = %s" % q(name),
            "description = %s" % q(desc), 'start_conditions = "[]"', 'fail_conditions = "[]"', 'on_start_facts = "{}"',
            "on_complete_facts = %s" % q(json.dumps({complete_fact: True})), 'on_fail_facts = "{}"', ""]


def task(out, tid, name, key, op, value):
    out += ["[task.%s]" % tid, "display_name = %s" % q(name), "description = %s" % q(name), "auto_start = true",
            "goal_conditions = %s" % q(cond(key, op, value)), ""]


def main():
    out = ["; CQ Quest goals, in galene's QuestSystem .cfg format (chapter > quest > task).",
           "; GENERATED by tools/build_quests.py - edit the script, not this file.", ""]
    for lv in range(1, LEVELS + 1):
        s = "" if lv == 1 else str(lv)
        fp = "" if lv == 1 else "l%d." % lv
        ch = "goals" + s
        out += ["[chapter.%s]" % ch, "display_name = %s" % q("Level %d" % lv),
                "description = %s" % q("Four goals: rules, shack, first contact, Morse code."), ""]
        quest(out, "rules" + s, ch, "Know the rules", "Learn the rules for your class and pass the quiz.", fp + "goal.rules")
        task(out, "rules%s.lessons" % s, "Read all lessons", fp + "rules.lessons_all", "eq", True)
        task(out, "rules%s.quiz" % s, "Pass the quiz", fp + "rules.quiz_passed", "eq", True)
        if lv == 1:
            task(out, "rules.callsign", "Find your callsign", "rules.callsign", "eq", True)
        quest(out, "shack" + s, ch, "Build your shack", "Learn about each part and earn it.", fp + "goal.shack")
        for pid, pname in PARTS:
            task(out, "shack%s.%s" % (s, pid), pname, "%sshack.%s" % (fp, pid), "eq", True)
        quest(out, "qso" + s, ch, "First contact", "Make a contact: tune in, answer, exchange details and say 73.", fp + "goal.qso")
        for k, name in [("tuned", "Find a station"), ("answered", "Answer the call"), ("exchanged", "Exchange details"),
                        ("spelled", "Spell your callsign"), ("done", "Say 73")]:
            task(out, "qso%s.%s" % (s, k), name, "%sqso.%s" % (fp, k), "eq", True)
        quest(out, "morse" + s, ch, "Learn Morse code", "Work through the Koch method levels.", fp + "goal.morse")
        task(out, "morse%s.level%d" % (s, MORSE_CAP[lv]), "Pass %d levels" % MORSE_CAP[lv], "morse.passed", "gte", MORSE_CAP[lv])
    with open(os.path.join(ROOT, "resources", "quests_cfg", "ham.cfg"), "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print("wrote ham.cfg")


if __name__ == "__main__":
    main()
