# -*- coding: utf-8 -*-
"""Levels 2 (intermediate) and 3 (advanced) for the 8 shack parts, EN + DE."""
from build_content import L, Q


def T(len_, lde, qs):
    return {"lesson": L(len_, lde), "questions": qs}


TIERS = {
    # ------------------------------------------------------------------ PSU
    "psu": {
        2: T(
            "A linear power supply uses a mains transformer, a rectifier and a large smoothing capacitor. It is heavy but quiet. A switching supply chops the voltage at tens of kilohertz, so it is light and efficient, but it can radiate noise into your receiver. Rectifying leaves a small leftover AC called ripple. To size a supply, use I = P / U: a radio that needs 138 W at 13.8 V draws 10 A.",
            "Ein Linearnetzteil besteht aus Netztransformator, Gleichrichter und einem großen Siebkondensator. Es ist schwer, aber leise. Ein Schaltnetzteil zerhackt die Spannung mit einigen zehn Kilohertz; es ist leicht und effizient, kann aber Störungen in deinen Empfänger einstreuen. Nach dem Gleichrichten bleibt eine kleine Restwechselspannung, die Brummspannung. Zur Dimensionierung gilt I = P / U: Ein Gerät mit 138 W bei 13,8 V nimmt 10 A auf.",
            [
                Q("A radio needs 138 W at 13.8 V. What current does it draw?",
                  "Ein Funkgerät braucht 138 W bei 13,8 V. Welchen Strom nimmt es auf?",
                  ["10 A", "1 A", "19 A", "100 A"], ["10 A", "1 A", "19 A", "100 A"]),
                Q("What is the main advantage of a switching supply over a linear one?",
                  "Was ist der Hauptvorteil eines Schaltnetzteils gegenüber einem Linearnetzteil?",
                  ["Smaller, lighter and more efficient", "It never produces any interference", "It needs no fuse", "It works without mains power"],
                  ["Kleiner, leichter und effizienter", "Es erzeugt nie Störungen", "Es braucht keine Sicherung", "Es funktioniert ohne Netzspannung"]),
                Q("A full-wave rectifier runs on 50 Hz mains. What is the ripple frequency?",
                  "Ein Zweiweggleichrichter arbeitet an 50-Hz-Netzspannung. Welche Frequenz hat die Brummspannung?",
                  ["100 Hz", "50 Hz", "25 Hz", "200 Hz"], ["100 Hz", "50 Hz", "25 Hz", "200 Hz"]),
                Q("Which part smooths the rectified voltage in a linear supply?",
                  "Welches Bauteil glättet im Linearnetzteil die gleichgerichtete Spannung?",
                  ["A large electrolytic capacitor", "A fuse", "A relay", "A loudspeaker"],
                  ["Ein großer Elektrolytkondensator", "Eine Sicherung", "Ein Relais", "Ein Lautsprecher"]),
            ]),
        3: T(
            "Efficiency is output power divided by input power. The difference is lost as heat, so a supply delivering 276 W at 80 % efficiency takes 345 W from the mains. A linear regulator turns the voltage difference times the current into heat. Load regulation tells how much the output voltage changes when the load current changes. Cables drop voltage too: by Ohm's law the drop is I × R, which matters at 20 A.",
            "Der Wirkungsgrad ist Ausgangsleistung geteilt durch Eingangsleistung. Der Rest geht als Wärme verloren: Ein Netzteil, das 276 W bei 80 % Wirkungsgrad liefert, nimmt 345 W aus dem Netz auf. Ein Linearregler setzt die Spannungsdifferenz mal Strom in Wärme um. Die Lastregelung gibt an, wie stark sich die Ausgangsspannung bei Laständerung ändert. Auch Kabel verursachen Spannungsabfall: nach dem Ohmschen Gesetz I × R, was bei 20 A zählt.",
            [
                Q("A supply delivers 276 W at 80 % efficiency. How much power does it take from the mains?",
                  "Ein Netzteil liefert 276 W bei 80 % Wirkungsgrad. Wie viel Leistung nimmt es aus dem Netz auf?",
                  ["345 W", "221 W", "276 W", "552 W"], ["345 W", "221 W", "276 W", "552 W"]),
                Q("A linear regulator gets 18 V and delivers 13.8 V at 10 A. How much heat does it dissipate?",
                  "Ein Linearregler bekommt 18 V und liefert 13,8 V bei 10 A. Wie viel Wärme verbraucht er?",
                  ["42 W", "138 W", "4.2 W", "180 W"], ["42 W", "138 W", "4,2 W", "180 W"]),
                Q("20 A flows through supply cables with a total resistance of 0.05 ohm. What is the voltage drop?",
                  "Durch Netzteilkabel mit 0,05 Ohm Gesamtwiderstand fließen 20 A. Wie groß ist der Spannungsabfall?",
                  ["1 V", "0.25 V", "10 V", "400 V"], ["1 V", "0,25 V", "10 V", "400 V"]),
                Q("What does good load regulation mean?",
                  "Was bedeutet gute Lastregelung?",
                  ["The output voltage barely changes when the load current changes", "The supply is very light", "The supply has no ripple at all", "The supply only works at low current"],
                  ["Die Ausgangsspannung ändert sich bei Laständerung kaum", "Das Netzteil ist sehr leicht", "Das Netzteil hat gar keine Brummspannung", "Das Netzteil funktioniert nur bei kleinem Strom"]),
            ]),
    },
    # -------------------------------------------------------------- ANTENNA
    "antenna": {
        2: T(
            "A half-wave dipole is about half a wavelength long, but real wire needs to be about 5 % shorter, so its length in metres is roughly 143 divided by the frequency in MHz. In coax the wave travels slower: the velocity factor is about 0.66 for solid polyethylene. Antenna gain is given in dBi (against an isotropic radiator) or dBd (against a dipole); 0 dBd equals 2.15 dBi. A balun joins a balanced dipole to unbalanced coax.",
            "Ein Halbwellendipol ist etwa eine halbe Wellenlänge lang, der reale Draht muss aber etwa 5 % kürzer sein; die Länge in Metern beträgt grob 143 geteilt durch die Frequenz in MHz. Im Koaxkabel breitet sich die Welle langsamer aus: Der Verkürzungsfaktor beträgt bei Vollpolyethylen etwa 0,66. Antennengewinn wird in dBi (gegenüber dem Kugelstrahler) oder dBd (gegenüber dem Dipol) angegeben; 0 dBd sind 2,15 dBi. Ein Balun verbindet einen symmetrischen Dipol mit unsymmetrischem Koax.",
            [
                Q("About how long is a real half-wave dipole for 7.1 MHz?",
                  "Wie lang ist ein realer Halbwellendipol für 7,1 MHz etwa?",
                  ["20 m", "10 m", "42 m", "5 m"], ["20 m", "10 m", "42 m", "5 m"]),
                Q("How long is a quarter-wave piece of coax (velocity factor 0.66) at 14 MHz?",
                  "Wie lang ist ein Viertelwellenstück Koax (Verkürzungsfaktor 0,66) bei 14 MHz?",
                  ["About 3.5 m", "About 5.4 m", "About 7.1 m", "About 1.8 m"], ["Etwa 3,5 m", "Etwa 5,4 m", "Etwa 7,1 m", "Etwa 1,8 m"]),
                Q("An antenna has 5 dBd gain. What is that in dBi?",
                  "Eine Antenne hat 5 dBd Gewinn. Wie viel sind das in dBi?",
                  ["7.15 dBi", "2.85 dBi", "5 dBi", "10.75 dBi"], ["7,15 dBi", "2,85 dBi", "5 dBi", "10,75 dBi"]),
                Q("What is the job of a balun at a dipole?",
                  "Was ist die Aufgabe eines Baluns am Dipol?",
                  ["Connect a balanced antenna to an unbalanced coax and reduce sheath currents", "Amplify the signal by 10 dB", "Lengthen the dipole electrically", "Filter out the mains hum"],
                  ["Eine symmetrische Antenne an unsymmetrisches Koax anpassen und Mantelwellen verringern", "Das Signal um 10 dB verstärken", "Den Dipol elektrisch verlängern", "Netzbrummen herausfiltern"]),
            ]),
        3: T(
            "ERP refers to a dipole, EIRP to an isotropic radiator: EIRP = ERP + 2.15 dB. Both equal transmitter power plus antenna gain minus feedline loss, calculated in dB. A half-wave dipole has roughly 73 ohms feed impedance in free space. A Yagi's front-to-back ratio compares forward and rearward signal; 20 dB means the rear signal is 100 times weaker in power. Feeding 73 ohms from 50-ohm coax gives SWR 1.46.",
            "ERP bezieht sich auf einen Dipol, EIRP auf den Kugelstrahler: EIRP = ERP + 2,15 dB. Beide ergeben sich aus Sendeleistung plus Antennengewinn minus Kabeldämpfung, gerechnet in dB. Ein Halbwellendipol hat im Freiraum etwa 73 Ohm Fußpunktwiderstand. Das Vor-Rück-Verhältnis einer Yagi vergleicht Vorwärts- und Rückwärtssignal; 20 dB bedeuten, dass das Signal nach hinten um den Faktor 100 schwächer in der Leistung ist. Speist man 73 Ohm aus 50-Ohm-Koax, ergibt sich ein SWR von 1,46.",
            [
                Q("100 W transmitter, feedline loss 2 dB, antenna gain 5 dBd. What is the ERP?",
                  "Sender mit 100 W, Kabeldämpfung 2 dB, Antennengewinn 5 dBd. Wie groß ist die ERP?",
                  ["About 200 W", "About 316 W", "About 63 W", "About 500 W"], ["Etwa 200 W", "Etwa 316 W", "Etwa 63 W", "Etwa 500 W"]),
                Q("An ERP of 100 W corresponds to which EIRP?",
                  "Welcher EIRP entspricht eine ERP von 100 W?",
                  ["About 164 W", "About 61 W", "100 W", "About 215 W"], ["Etwa 164 W", "Etwa 61 W", "100 W", "Etwa 215 W"]),
                Q("A Yagi has a front-to-back ratio of 20 dB. A signal from behind arrives with what power compared to the same signal from the front?",
                  "Eine Yagi hat ein Vor-Rück-Verhältnis von 20 dB. Mit welcher Leistung kommt ein Signal von hinten an, verglichen mit dem gleichen Signal von vorn?",
                  ["1/100", "1/20", "1/10", "1/2"], ["1/100", "1/20", "1/10", "1/2"]),
                Q("A half-wave dipole (73 ohms) is fed directly with 50-ohm coax. Which SWR results?",
                  "Ein Halbwellendipol (73 Ohm) wird direkt mit 50-Ohm-Koax gespeist. Welches SWR ergibt sich?",
                  ["About 1.5:1", "1:1", "About 2.5:1", "About 3.6:1"], ["Etwa 1,5:1", "1:1", "Etwa 2,5:1", "Etwa 3,6:1"]),
            ]),
    },
    # ---------------------------------------------------------- TRANSCEIVER
    "transceiver": {
        2: T(
            "Each mode needs a different bandwidth: an SSB voice signal uses about 2.4 to 3 kHz, CW only a few hundred hertz, and FM voice on VHF more than 10 kHz. A narrower receiver filter lets in less noise: noise power is proportional to bandwidth. By convention, amateurs use lower sideband below 10 MHz and upper sideband above. Digital modes such as FT8 need a PC clock accurate to about a second.",
            "Jede Betriebsart braucht eine andere Bandbreite: Ein SSB-Sprachsignal belegt etwa 2,4 bis 3 kHz, CW nur wenige hundert Hertz, FM-Sprache auf UKW mehr als 10 kHz. Ein schmaleres Empfängerfilter lässt weniger Rauschen durch: Die Rauschleistung ist proportional zur Bandbreite. Üblicherweise nutzt man unterhalb von 10 MHz das untere Seitenband (LSB), darüber das obere (USB). Digitale Betriebsarten wie FT8 brauchen eine auf etwa eine Sekunde genaue PC-Uhr.",
            [
                Q("Roughly how wide is a normal SSB voice signal?",
                  "Wie breit ist ein normales SSB-Sprachsignal ungefähr?",
                  ["2.4 to 3 kHz", "50 Hz", "15 to 20 kHz", "200 kHz"], ["2,4 bis 3 kHz", "50 Hz", "15 bis 20 kHz", "200 kHz"]),
                Q("You narrow the receiver filter from 2400 Hz to 600 Hz. How much less noise power gets through?",
                  "Du verkleinerst die Empfängerbandbreite von 2400 Hz auf 600 Hz. Um wie viel sinkt die Rauschleistung?",
                  ["About 6 dB", "About 3 dB", "About 4 dB", "About 12 dB"], ["Etwa 6 dB", "Etwa 3 dB", "Etwa 4 dB", "Etwa 12 dB"]),
                Q("Which sideband is conventionally used on the 40 m band?",
                  "Welches Seitenband wird auf dem 40-m-Band üblicherweise benutzt?",
                  ["Lower sideband (LSB)", "Upper sideband (USB)", "Both at once", "Neither, only AM"], ["Unteres Seitenband (LSB)", "Oberes Seitenband (USB)", "Beide gleichzeitig", "Keines, nur AM"]),
                Q("Why must the PC clock be accurate for FT8?",
                  "Warum muss die PC-Uhr für FT8 genau gehen?",
                  ["Transmissions are sent in fixed time slots that stations must share", "The antenna needs it for tuning", "It sets the transmit power", "It charges the battery"],
                  ["Die Aussendungen laufen in festen Zeitfenstern, die alle Stationen teilen müssen", "Die Antenne braucht sie zum Abstimmen", "Sie bestimmt die Sendeleistung", "Sie lädt den Akku"]),
            ]),
        3: T(
            "A superheterodyne receiver mixes the signal with a local oscillator to a fixed intermediate frequency (IF), where filtering is easy. A second frequency, the image, also produces the same IF and must be blocked by front-end filters. Dynamic range is the span between the noise floor and the strongest signal handled without distortion. Oscillators are usually PLL synthesizers locked to a crystal; an SDR digitises the signal and processes it in software.",
            "Ein Superhet-Empfänger mischt das Signal mit einem Oszillator auf eine feste Zwischenfrequenz (ZF), wo sich gut filtern lässt. Eine zweite Frequenz, die Spiegelfrequenz, ergibt dieselbe ZF und muss von Eingangsfiltern unterdrückt werden. Der Dynamikbereich ist der Abstand zwischen Rauschgrenze und dem stärksten Signal, das ohne Verzerrung verarbeitet wird. Oszillatoren sind meist PLL-Synthesizer, die auf einen Quarz geregelt sind; ein SDR digitalisiert das Signal und verarbeitet es per Software.",
            [
                Q("An IF of 9 MHz is used and the oscillator runs above the signal. Receiving 14.2 MHz, where is the image frequency?",
                  "Es wird eine ZF von 9 MHz genutzt, der Oszillator liegt über dem Signal. Beim Empfang von 14,2 MHz: Wo liegt die Spiegelfrequenz?",
                  ["32.2 MHz", "23.2 MHz", "5.2 MHz", "18.0 MHz"], ["32,2 MHz", "23,2 MHz", "5,2 MHz", "18,0 MHz"]),
                Q("What does the dynamic range of a receiver describe?",
                  "Was beschreibt der Dynamikbereich eines Empfängers?",
                  ["The span between the noise floor and the strongest undistorted signal", "How many bands it can tune", "The range of the audio volume knob", "The distance to the nearest station"],
                  ["Den Abstand zwischen Rauschgrenze und stärkstem unverzerrtem Signal", "Wie viele Bänder er abstimmen kann", "Den Bereich des Lautstärkereglers", "Die Entfernung zur nächsten Station"]),
                Q("On a low HF band with a good antenna, what does an extra preamplifier usually do?",
                  "Was bewirkt ein zusätzlicher Vorverstärker auf einem niedrigen Kurzwellenband mit guter Antenne meist?",
                  ["Adds little benefit and raises the risk of overload", "Doubles the dynamic range", "Removes the image frequency", "Lowers the SWR"],
                  ["Bringt wenig Nutzen und erhöht die Übersteuerungsgefahr", "Verdoppelt den Dynamikbereich", "Beseitigt die Spiegelfrequenz", "Senkt das SWR"]),
                Q("What does a PLL synthesizer do?",
                  "Was macht ein PLL-Synthesizer?",
                  ["Generates stable frequencies locked to a crystal reference", "Amplifies the audio", "Measures the antenna impedance", "Rectifies the mains voltage"],
                  ["Erzeugt stabile Frequenzen, die auf eine Quarzreferenz geregelt sind", "Verstärkt das Tonsignal", "Misst die Antennenimpedanz", "Richtet die Netzspannung gleich"]),
            ]),
    },
    # ------------------------------------------------------------------ MIC
    "mic": {
        2: T(
            "Dynamic microphones are rugged and need no power. Condenser (including electret) microphones are more sensitive and need a small bias voltage. A VOX circuit switches the transmitter on automatically when it hears your voice. The ALC meter shows how hard you drive the transmitter: adjust the microphone gain so it moves only on voice peaks and stays within its marked zone. A speech processor raises the average talk power.",
            "Dynamische Mikrofone sind robust und brauchen keine Speisung. Kondensatormikrofone (auch Elektret) sind empfindlicher und brauchen eine kleine Vorspannung. Eine VOX schaltet den Sender automatisch ein, sobald sie deine Stimme hört. Das ALC-Instrument zeigt, wie stark du den Sender aussteuerst: Stelle die Mikrofonverstärkung so ein, dass es nur bei Sprachspitzen ausschlägt und im markierten Bereich bleibt. Ein Sprachprozessor erhöht die mittlere Sprechleistung.",
            [
                Q("Which microphone type needs a bias or phantom voltage?",
                  "Welcher Mikrofontyp braucht eine Vorspannung oder Phantomspeisung?",
                  ["Condenser / electret", "Dynamic", "Moving-coil only", "Every type"], ["Kondensator / Elektret", "Dynamisch", "Nur Tauchspulmikrofone", "Jeder Typ"]),
                Q("What does VOX do?",
                  "Was macht die VOX?",
                  ["Switches to transmit when it detects your voice", "Raises the frequency", "Measures SWR", "Stores the log"],
                  ["Schaltet auf Senden, wenn sie deine Stimme erkennt", "Erhöht die Frequenz", "Misst das SWR", "Speichert das Logbuch"]),
                Q("How should the ALC meter behave while you speak in SSB?",
                  "Wie sollte sich das ALC-Instrument beim SSB-Sprechen verhalten?",
                  ["Move only on voice peaks, within its marked zone", "Stay pinned at full scale", "Stay at zero", "Swing back and forth across the whole scale"],
                  ["Nur bei Sprachspitzen im markierten Bereich ausschlagen", "Dauernd am Anschlag stehen", "Bei null bleiben", "Über die ganze Skala pendeln"]),
                Q("What does a speech processor (compressor) do?",
                  "Was macht ein Sprachprozessor (Kompressor)?",
                  ["Raises the average level relative to the peaks", "Lowers the carrier frequency", "Makes the antenna longer", "Removes the sidebands"],
                  ["Hebt den mittleren Pegel gegenüber den Spitzen an", "Senkt die Trägerfrequenz", "Verlängert die Antenne", "Entfernt die Seitenbänder"]),
            ]),
        3: T(
            "In FM, the deviation is how far the carrier frequency swings. The modulation index is deviation divided by the audio frequency, and Carson's rule estimates bandwidth as B = 2 × (deviation + highest audio frequency). Voltage ratios in dB use 20 × log10, so a tenfold voltage is +20 dB. Overdriving an SSB transmitter creates intermodulation products, called splatter, that spread beyond the normal bandwidth and disturb neighbours.",
            "Bei FM ist der Frequenzhub das Ausmaß, um das die Trägerfrequenz schwingt. Der Modulationsindex ist Hub geteilt durch Modulationsfrequenz, und die Carson-Regel schätzt die Bandbreite als B = 2 × (Hub + höchste Modulationsfrequenz). Spannungsverhältnisse in dB rechnet man mit 20 × log10: Die zehnfache Spannung sind +20 dB. Übersteuert man einen SSB-Sender, entstehen Intermodulationsprodukte (Splatter), die über die normale Bandbreite hinausreichen und Nachbarn stören.",
            [
                Q("An FM signal has 3 kHz deviation and a 1 kHz audio tone. What is the modulation index?",
                  "Ein FM-Signal hat 3 kHz Hub bei einem 1-kHz-Ton. Wie groß ist der Modulationsindex?",
                  ["3", "0.33", "4", "1"], ["3", "0,33", "4", "1"]),
                Q("Deviation 3 kHz, highest audio frequency 3 kHz. What bandwidth does Carson's rule give?",
                  "Hub 3 kHz, höchste Modulationsfrequenz 3 kHz. Welche Bandbreite liefert die Carson-Regel?",
                  ["12 kHz", "6 kHz", "9 kHz", "3 kHz"], ["12 kHz", "6 kHz", "9 kHz", "3 kHz"]),
                Q("The microphone voltage rises from 10 mV to 100 mV. By how many dB?",
                  "Die Mikrofonspannung steigt von 10 mV auf 100 mV. Um wie viel dB?",
                  ["20 dB", "10 dB", "40 dB", "100 dB"], ["20 dB", "10 dB", "40 dB", "100 dB"]),
                Q("What is the typical result of overdriving an SSB transmitter?",
                  "Was ist die typische Folge einer Übersteuerung eines SSB-Senders?",
                  ["Splatter: distortion products outside the normal bandwidth", "A longer antenna", "A lower noise floor in the receiver", "A narrower signal"],
                  ["Splatter: Verzerrungsprodukte außerhalb der normalen Bandbreite", "Eine längere Antenne", "Ein geringeres Empfängerrauschen", "Ein schmaleres Signal"]),
            ]),
    },
    # -------------------------------------------------------------- SPEAKER
    "speaker": {
        2: T(
            "Speakers usually have 4 or 8 ohms. Connect two in parallel and the impedance falls (two 8-ohm speakers give 4 ohms); in series it adds up. Audio power follows P = U² / R. A narrow audio filter helps with CW, because only your tone passes and the noise around it is cut. A level change of 3 dB means the power doubles; DSP noise reduction cleans up weak signals.",
            "Lautsprecher haben meist 4 oder 8 Ohm. Schaltet man zwei parallel, sinkt die Impedanz (zweimal 8 Ohm ergeben 4 Ohm); in Reihe addiert sie sich. Die Tonleistung folgt P = U² / R. Ein schmales NF-Filter hilft beim CW-Empfang, weil nur dein Ton durchkommt und das Rauschen drumherum abgeschnitten wird. Eine Pegeländerung von 3 dB bedeutet doppelte Leistung; DSP-Rauschminderung säubert schwache Signale.",
            [
                Q("Two 8-ohm speakers are connected in parallel. What is the total impedance?",
                  "Zwei 8-Ohm-Lautsprecher werden parallel geschaltet. Wie groß ist die Gesamtimpedanz?",
                  ["4 ohms", "16 ohms", "8 ohms", "2 ohms"], ["4 Ohm", "16 Ohm", "8 Ohm", "2 Ohm"]),
                Q("4 V (RMS) are applied to an 8-ohm speaker. What power does it receive?",
                  "An einem 8-Ohm-Lautsprecher liegen 4 V (Effektivwert). Welche Leistung nimmt er auf?",
                  ["2 W", "0.5 W", "32 W", "4 W"], ["2 W", "0,5 W", "32 W", "4 W"]),
                Q("Why use a narrow audio filter for CW?",
                  "Warum nutzt man für CW ein schmales NF-Filter?",
                  ["Only the tone passes and noise outside it is cut", "It makes the transmitter stronger", "It lowers the SWR", "It raises the frequency of the tone"],
                  ["Nur der Ton kommt durch und Rauschen außerhalb wird abgeschnitten", "Es macht den Sender stärker", "Es senkt das SWR", "Es erhöht die Tonfrequenz"]),
                Q("An audio amplifier's output power is raised by 3 dB. What happens to the power?",
                  "Die Ausgangsleistung eines NF-Verstärkers steigt um 3 dB. Was passiert mit der Leistung?",
                  ["It roughly doubles", "It triples", "It rises by 3 W", "It stays the same"],
                  ["Sie verdoppelt sich ungefähr", "Sie verdreifacht sich", "Sie steigt um 3 W", "Sie bleibt gleich"]),
            ]),
        3: T(
            "Decibels compare powers with 10 × log10 and voltages with 20 × log10: doubling power is +3 dB, doubling voltage +6 dB, a tenfold power +10 dB. Amplifier output voltage follows U = √(P × R). Digital audio processing samples the signal: by the Nyquist theorem the sampling rate must be more than twice the highest frequency. DSP filters and noise reduction work on these samples.",
            "Dezibel vergleichen Leistungen mit 10 × log10 und Spannungen mit 20 × log10: Doppelte Leistung sind +3 dB, doppelte Spannung +6 dB, zehnfache Leistung +10 dB. Die Ausgangsspannung eines Verstärkers folgt U = √(P × R). Digitale Signalverarbeitung tastet das Signal ab: Nach dem Nyquist-Theorem muss die Abtastrate mehr als doppelt so hoch sein wie die höchste Frequenz. DSP-Filter und Rauschminderung arbeiten mit diesen Abtastwerten.",
            [
                Q("Amplifier output power rises from 1 W to 10 W. How many dB is that?",
                  "Die Ausgangsleistung eines Verstärkers steigt von 1 W auf 10 W. Wie viele dB sind das?",
                  ["+10 dB", "+20 dB", "+3 dB", "+100 dB"], ["+10 dB", "+20 dB", "+3 dB", "+100 dB"]),
                Q("The audio voltage doubles. By how many dB does the level rise?",
                  "Die NF-Spannung verdoppelt sich. Um wie viele dB steigt der Pegel?",
                  ["About 6 dB", "About 3 dB", "About 12 dB", "About 2 dB"], ["Etwa 6 dB", "Etwa 3 dB", "Etwa 12 dB", "Etwa 2 dB"]),
                Q("An amplifier delivers 50 W into 8 ohms. What RMS voltage is across the speaker?",
                  "Ein Verstärker liefert 50 W an 8 Ohm. Welche Effektivspannung liegt am Lautsprecher?",
                  ["20 V", "6.3 V", "400 V", "40 V"], ["20 V", "6,3 V", "400 V", "40 V"]),
                Q("Speech audio up to 3 kHz is digitised. What sampling rate is the theoretical minimum?",
                  "Sprache bis 3 kHz wird digitalisiert. Welche Abtastrate ist theoretisch mindestens nötig?",
                  ["More than 6 kHz", "More than 3 kHz", "More than 1.5 kHz", "More than 12 kHz"],
                  ["Mehr als 6 kHz", "Mehr als 3 kHz", "Mehr als 1,5 kHz", "Mehr als 12 kHz"]),
            ]),
    },
    # ------------------------------------------------------------------ SWR
    "swr": {
        2: T(
            "SWR is the ratio between load and line impedance, whichever is larger over the smaller. A 100-ohm load on 50-ohm coax gives 2:1. The reflection coefficient ρ = (SWR − 1) / (SWR + 1), and reflected power is ρ². At 1.5:1, only 4 % of the power is reflected, which is perfectly fine. An antenna tuner (ATU) does not change the antenna, but makes the radio see 50 ohms.",
            "Das SWR ist das Verhältnis von Last- und Leitungsimpedanz, der größere Wert geteilt durch den kleineren. Eine 100-Ohm-Last an 50-Ohm-Koax ergibt 2:1. Der Reflexionsfaktor ist r = (SWR − 1) / (SWR + 1), die reflektierte Leistung r². Bei 1,5:1 werden nur 4 % der Leistung reflektiert, das ist völlig in Ordnung. Ein Antennentuner (ATU) verändert die Antenne nicht, sorgt aber dafür, dass das Funkgerät 50 Ohm sieht.",
            [
                Q("A 100-ohm load is connected to 50-ohm coax. What is the SWR?",
                  "Eine 100-Ohm-Last hängt an 50-Ohm-Koax. Wie groß ist das SWR?",
                  ["2:1", "50:1", "0.5:1", "5:1"], ["2:1", "50:1", "0,5:1", "5:1"]),
                Q("At SWR 1.5:1, about what share of the power is reflected?",
                  "Bei einem SWR von 1,5:1: Welcher Anteil der Leistung wird ungefähr reflektiert?",
                  ["4 %", "20 %", "50 %", "1.5 %"], ["4 %", "20 %", "50 %", "1,5 %"]),
                Q("What does an ATU do?",
                  "Was macht ein Antennentuner (ATU)?",
                  ["Transforms the impedance so the radio sees about 50 ohms", "Makes the antenna physically longer", "Amplifies the signal", "Removes the reflected power from the antenna"],
                  ["Transformiert die Impedanz, sodass das Funkgerät etwa 50 Ohm sieht", "Verlängert die Antenne physisch", "Verstärkt das Signal", "Entfernt die reflektierte Leistung aus der Antenne"]),
                Q("Which SWR is normally still acceptable?",
                  "Welches SWR ist normalerweise noch akzeptabel?",
                  ["1.5:1", "10:1", "Infinite", "5:1"], ["1,5:1", "10:1", "Unendlich", "5:1"]),
            ]),
        3: T(
            "Reflection coefficient ρ = (Z_L − Z_0) / (Z_L + Z_0); SWR = (1 + ρ) / (1 − ρ). Reflected power is ρ² of the forward power, and return loss is −20 × log10(ρ) in dB. Coax loss hides a bad antenna: the reflected wave is attenuated twice on its way back, so the SWR measured at the radio looks lower than at the antenna. A low reading through lossy cable proves little.",
            "Reflexionsfaktor r = (Z_L − Z_0) / (Z_L + Z_0); SWR = (1 + r) / (1 − r). Die reflektierte Leistung beträgt r² der Vorwärtsleistung, die Rückflussdämpfung −20 × log10(r) in dB. Kabeldämpfung kaschiert eine schlechte Antenne: Die reflektierte Welle wird auf dem Rückweg zusätzlich gedämpft, daher sieht das SWR am Funkgerät besser aus als an der Antenne. Ein niedriger Wert über ein verlustreiches Kabel beweist wenig.",
            [
                Q("What is the reflection coefficient at SWR 3:1?",
                  "Wie groß ist der Reflexionsfaktor bei SWR 3:1?",
                  ["0.5", "0.33", "0.67", "0.75"], ["0,5", "0,33", "0,67", "0,75"]),
                Q("100 W forward power, SWR 3:1, lossless line. How much power does the load absorb?",
                  "100 W Vorwärtsleistung, SWR 3:1, verlustfreie Leitung. Wie viel Leistung nimmt die Last auf?",
                  ["75 W", "25 W", "50 W", "67 W"], ["75 W", "25 W", "50 W", "67 W"]),
                Q("A return loss of 20 dB corresponds to about which SWR?",
                  "Einer Rückflussdämpfung von 20 dB entspricht etwa welches SWR?",
                  ["1.2:1", "2:1", "1.5:1", "3:1"], ["1,2:1", "2:1", "1,5:1", "3:1"]),
                Q("Long, lossy coax shows 1.5:1 at the radio, but the antenna is badly matched. What is the explanation?",
                  "Langes, verlustreiches Koax zeigt am Funkgerät 1,5:1, die Antenne ist aber schlecht angepasst. Wie ist das zu erklären?",
                  ["Much of the power is lost in the cable, which hides the mismatch", "The antenna is actually perfect", "The SWR meter measures voltage only", "Coax cable raises the SWR"],
                  ["Viel Leistung geht im Kabel verloren, das die Fehlanpassung verdeckt", "Die Antenne ist tatsächlich perfekt", "Das SWR-Meter misst nur Spannung", "Koaxkabel erhöht das SWR"]),
            ]),
    },
    # ------------------------------------------------------------------ KEY
    "key": {
        2: T(
            "Morse speed is measured in words per minute (WPM) using the word PARIS, which is 50 dit lengths long. So one dit lasts 1.2 / WPM seconds: at 20 WPM, 60 ms. Gaps matter as well: 1 dit between elements, 3 dits between letters and 7 dits between words. An iambic paddle keyer sends alternating dits and dahs automatically while you squeeze both paddles.",
            "Die Morsegeschwindigkeit misst man in Wörtern pro Minute (WPM) mit dem Wort PARIS, das 50 Dit-Längen lang ist. Ein Dit dauert also 1,2 / WPM Sekunden: bei 20 WPM 60 ms. Auch die Pausen zählen: 1 Dit zwischen den Zeichen, 3 Dits zwischen Buchstaben und 7 Dits zwischen Wörtern. Ein Iambic-Paddle sendet abwechselnd Dits und Dahs automatisch, solange du beide Paddles drückst.",
            [
                Q("How long is one dit at 20 WPM?",
                  "Wie lang ist ein Dit bei 20 WPM?",
                  ["60 ms", "120 ms", "30 ms", "600 ms"], ["60 ms", "120 ms", "30 ms", "600 ms"]),
                Q("How many dit lengths does the standard word PARIS take?",
                  "Wie viele Dit-Längen braucht das Standardwort PARIS?",
                  ["50", "25", "100", "10"], ["50", "25", "100", "10"]),
                Q("How long is the gap between two words?",
                  "Wie lang ist die Pause zwischen zwei Wörtern?",
                  ["7 dit lengths", "3 dit lengths", "1 dit length", "10 dit lengths"],
                  ["7 Dit-Längen", "3 Dit-Längen", "1 Dit-Länge", "10 Dit-Längen"]),
                Q("What does an iambic paddle do when you squeeze both paddles?",
                  "Was macht ein Iambic-Paddle, wenn du beide Paddles drückst?",
                  ["Sends alternating dits and dahs", "Sends a continuous tone", "Stops sending", "Sends only dahs"],
                  ["Sendet abwechselnd Dits und Dahs", "Sendet einen Dauerton", "Sendet nichts mehr", "Sendet nur Dahs"]),
            ]),
        3: T(
            "If the transmitter switches on and off too abruptly, the signal gets key clicks: sharp edges that spread over neighbouring frequencies. Rounding the rise and fall of the keyed envelope to a few milliseconds cures this. Full break-in (QSK) switches between transmit and receive so fast that you can hear the other station between your own dits. Dit length is 1.2 / WPM seconds; a letter's length is the sum of its dits, dahs and gaps.",
            "Schaltet der Sender zu abrupt ein und aus, entstehen Tastklicks: steile Flanken, die sich auf Nachbarfrequenzen ausbreiten. Das Abrunden von Anstieg und Abfall der getasteten Hüllkurve auf einige Millisekunden behebt das. Beim vollen Break-in (QSK) wird so schnell zwischen Senden und Empfang umgeschaltet, dass du die Gegenstation zwischen deinen eigenen Dits hörst. Die Dit-Länge beträgt 1,2 / WPM Sekunden; die Länge eines Buchstabens ergibt sich aus Dits, Dahs und Pausen.",
            [
                Q("What causes key clicks?",
                  "Was verursacht Tastklicks?",
                  ["Too sharp rise and fall of the keyed signal", "A too long antenna", "A too slow keying speed", "Too much speaker volume"],
                  ["Zu steile Flanken des getasteten Signals", "Eine zu lange Antenne", "Eine zu niedrige Tastgeschwindigkeit", "Zu hohe Lautsprecherlautstärke"]),
                Q("The dit length is 40 ms. What is the speed?",
                  "Die Dit-Länge beträgt 40 ms. Wie hoch ist die Geschwindigkeit?",
                  ["30 WPM", "24 WPM", "40 WPM", "15 WPM"], ["30 WPM", "24 WPM", "40 WPM", "15 WPM"]),
                Q("What does full break-in (QSK) allow?",
                  "Was ermöglicht volles Break-in (QSK)?",
                  ["Hearing the other station between your dits and dahs", "Sending without an antenna", "Doubling the power", "Sending faster than 100 WPM"],
                  ["Die Gegenstation zwischen deinen Dits und Dahs zu hören", "Senden ohne Antenne", "Die Leistung zu verdoppeln", "Schneller als 100 WPM zu senden"]),
                Q("At 24 WPM (dit = 50 ms), how long does the letter K (dah dit dah) take, including the gaps between elements?",
                  "Bei 24 WPM (Dit = 50 ms): Wie lange dauert der Buchstabe K (Dah Dit Dah) einschließlich der Pausen zwischen den Elementen?",
                  ["450 ms", "350 ms", "250 ms", "600 ms"], ["450 ms", "350 ms", "250 ms", "600 ms"]),
            ]),
    },
    # -------------------------------------------------------------- LOGBOOK
    "logbook": {
        2: T(
            "Always log in UTC, which has no daylight saving. To convert, subtract the local offset: Central European Time (CET) is UTC+1, summer time (CEST) is UTC+2. So 20:30 CEST is 18:30 UTC. Near midnight the date changes too. In the RST report, R is readability (1 to 5), S is signal strength (1 to 9), and T is tone (1 to 9, CW only).",
            "Logge immer in UTC, das keine Sommerzeit kennt. Zum Umrechnen ziehst du den lokalen Versatz ab: Mitteleuropäische Zeit (MEZ) ist UTC+1, die Sommerzeit (MESZ) UTC+2. Also sind 20:30 MESZ gleich 18:30 UTC. Kurz nach Mitternacht ändert sich auch das Datum. Im Rapport RST steht R für Lesbarkeit (1 bis 5), S für Signalstärke (1 bis 9) und T für den Ton (1 bis 9, nur bei CW).",
            [
                Q("A contact starts at 20:30 CEST (UTC+2). What is that in UTC?",
                  "Eine Verbindung beginnt um 20:30 MESZ (UTC+2). Wie viel Uhr ist das in UTC?",
                  ["18:30 UTC", "22:30 UTC", "19:30 UTC", "20:30 UTC"], ["18:30 UTC", "22:30 UTC", "19:30 UTC", "20:30 UTC"]),
                Q("It is 00:30 CEST on 12 June. What are date and time in UTC?",
                  "Es ist 00:30 MESZ am 12. Juni. Welches Datum und welche Uhrzeit gelten in UTC?",
                  ["22:30 UTC on 11 June", "02:30 UTC on 12 June", "22:30 UTC on 12 June", "23:30 UTC on 11 June"],
                  ["22:30 UTC am 11. Juni", "02:30 UTC am 12. Juni", "22:30 UTC am 12. Juni", "23:30 UTC am 11. Juni"]),
                Q("Why do amateurs log in UTC?",
                  "Warum loggen Funkamateure in UTC?",
                  ["It is the same worldwide and has no daylight saving", "It is the local time of the operator", "It changes with the sunrise", "It is required by the radio"],
                  ["Es gilt weltweit einheitlich und kennt keine Sommerzeit", "Es ist die Ortszeit des Funkers", "Es ändert sich mit dem Sonnenaufgang", "Das Funkgerät verlangt es"]),
                Q("In the CW report RST 579, what does the last digit describe?",
                  "Im CW-Rapport RST 579: Was beschreibt die letzte Ziffer?",
                  ["Tone quality", "Signal strength", "Readability", "Frequency"], ["Die Tonqualität", "Die Signalstärke", "Die Lesbarkeit", "Die Frequenz"]),
            ]),
        3: T(
            "A good log entry holds date, UTC time, both callsigns, band or frequency, mode and reports. ADIF is the standard file format to exchange logs between programs and QSL services. The Maidenhead grid locator, like JO62QM, has two letters (field), two digits (square) and two letters (subsquare); it shows your position in a short code. When converting, remember the sign: UTC−5 means add 5 hours to get UTC.",
            "Ein guter Logeintrag enthält Datum, UTC-Zeit, beide Rufzeichen, Band oder Frequenz, Betriebsart und Rapporte. ADIF ist das Standarddateiformat, um Logs zwischen Programmen und QSL-Diensten auszutauschen. Der Maidenhead-Locator, etwa JO62QM, besteht aus zwei Buchstaben (Feld), zwei Ziffern (Quadrat) und zwei Buchstaben (Subquadrat); er beschreibt deine Position in einem kurzen Code. Beim Umrechnen auf das Vorzeichen achten: Bei UTC−5 addierst du 5 Stunden, um UTC zu erhalten.",
            [
                Q("What is ADIF used for?",
                  "Wofür wird ADIF verwendet?",
                  ["Exchanging log data between programs and services", "Tuning the antenna", "Measuring the SWR", "Encoding Morse"],
                  ["Logdaten zwischen Programmen und Diensten austauschen", "Die Antenne abstimmen", "Das SWR messen", "Morsezeichen codieren"]),
                Q("How is a six-character Maidenhead locator like JO62QM structured?",
                  "Wie ist ein sechsstelliger Maidenhead-Locator wie JO62QM aufgebaut?",
                  ["2 letters, 2 digits, 2 letters", "6 digits", "3 letters, 3 digits", "2 digits, 2 letters, 2 digits"],
                  ["2 Buchstaben, 2 Ziffern, 2 Buchstaben", "6 Ziffern", "3 Buchstaben, 3 Ziffern", "2 Ziffern, 2 Buchstaben, 2 Ziffern"]),
                Q("Which set of data is enough to match a QSO with your partner's log?",
                  "Mit welchen Angaben lässt sich ein QSO mit dem Log des Partners abgleichen?",
                  ["Date, UTC time, callsigns, band and mode", "Local time, weather and antenna height", "Only the RST report", "Transmitter power and supply voltage"],
                  ["Datum, UTC-Zeit, Rufzeichen, Band und Betriebsart", "Ortszeit, Wetter und Antennenhöhe", "Nur der RST-Rapport", "Sendeleistung und Versorgungsspannung"]),
                Q("A contact took place at 21:00 local time in a zone at UTC−5. What is the UTC time?",
                  "Eine Verbindung fand um 21:00 Ortszeit in einer Zone mit UTC−5 statt. Welche UTC-Zeit gilt?",
                  ["02:00 UTC on the next day", "16:00 UTC on the same day", "02:00 UTC on the same day", "21:00 UTC on the next day"],
                  ["02:00 UTC am nächsten Tag", "16:00 UTC am selben Tag", "02:00 UTC am selben Tag", "21:00 UTC am nächsten Tag"]),
            ]),
    },
}
