"""Levels 2 and 3 for the US and UK primers (original text, NOT official exam pools).

us_levels() -> [General, Amateur Extra]
uk_levels() -> [Intermediate, Full]
Facts checked against FCC Part 97 (47 CFR 97.103/105/111/113/115/119/301/313/503) and
Ofcom's amateur radio licence framework (statement Dec 2023, notice of variation Feb 2024,
licensee guidance Oct 2025) plus RSGB exam pages.
"""


def L(en, de):
    return {"en": en, "de": de}


def Q(qen, qde, aen, ade, c=0):
    """Question. Answers are given with the correct one FIRST (c = index of correct)."""
    return {"q": L(qen, qde), "a": [L(x, y) for x, y in zip(aen, ade)], "c": c}


def _lesson(ten, tde, ben, bde):
    return {"t": L(ten, tde), "b": L(ben, bde)}


# ----------------------------------------------------------------------------------------
# United States
# ----------------------------------------------------------------------------------------
def us_levels():
    general = {
        "class": L("General", "General"),
        "licence": L("General class", "General-Klasse"),
        "lessons": [
            _lesson(
                "What General adds",
                "Was General dazu bringt",
                "The General class opens most of the HF bands. You get CW and data on 30 metres, phone and more on 17, 12 and 10 metres, and large parts of 80, 40, 20 and 15 metres. A few segments stay reserved for Amateur Extra. To earn it you pass Element 3: 35 questions, 26 correct, on top of the Technician exam.",
                "Die General-Klasse öffnet dir den Großteil der Kurzwelle. Du bekommst Telegrafie und Datenbetrieb auf 30 Metern, Telefonie und mehr auf 17, 12 und 10 Metern sowie große Teile von 80, 40, 20 und 15 Metern. Einige Abschnitte bleiben der Klasse Amateur Extra vorbehalten. Dafür bestehst du Element 3: 35 Fragen, 26 richtige Antworten, zusätzlich zur Technician-Prüfung."),
            _lesson(
                "Power and identification",
                "Leistung und Kennung",
                "The power limit for US amateurs is 1500 watts PEP, but you must always use no more than the minimum power needed for the contact. On 30 metres (10.10 to 10.15 MHz) the limit is lower, 200 watts PEP. Identify with your callsign at the end of each communication and at least every 10 minutes during it. On phone, use English.",
                "Die Leistungsgrenze für US-Funkamateure liegt bei 1500 Watt PEP, du sollst aber immer nur so viel Leistung nutzen, wie für die Verbindung nötig ist. Auf 30 Metern (10,10 bis 10,15 MHz) gilt die niedrigere Grenze von 200 Watt PEP. Nenne dein Rufzeichen am Ende jeder Verbindung und mindestens alle 10 Minuten währenddessen. In Telefonie sprichst du Englisch."),
            _lesson(
                "Control operator and third parties",
                "Control Operator und Dritte",
                "The control operator is the licensed person in charge of the station at that moment. The station may only be used within the privileges of the control operator's own class. Third parties may take part in a contact if the control operator is present and supervises them all the time. Messages to foreign countries need an agreement between that country and the US, unless it is an emergency.",
                "Der Control Operator ist die lizenzierte Person, die die Station in diesem Moment verantwortet. Die Station darf nur im Rahmen der Rechte seiner eigenen Klasse betrieben werden. Dritte dürfen an einer Verbindung teilnehmen, wenn der Control Operator anwesend ist und sie ständig beaufsichtigt. Für Nachrichten ins Ausland muss es ein Abkommen zwischen dem Land und den USA geben, außer im Notfall."),
            _lesson(
                "Upgrading and operating tips",
                "Aufstieg und Betriebstipps",
                "After you pass, you may use General privileges as soon as your upgrade appears in the FCC licence database, and you keep your callsign. You can also apply for a vanity callsign of your own class or lower; for General that means three-letter suffix calls. Plan your band by the time of day: 20 metres carries far in daylight, 80 and 40 metres come alive at night.",
                "Nach bestandener Prüfung darfst du die General-Rechte nutzen, sobald dein Aufstieg in der FCC-Datenbank steht, und du behältst dein Rufzeichen. Außerdem kannst du ein Wunschrufzeichen deiner oder einer niedrigeren Klasse beantragen; für General sind das Rufzeichen mit drei Buchstaben im Suffix. Wähle das Band nach der Tageszeit: 20 Meter trägt tagsüber weit, 80 und 40 Meter erwachen nachts."),
        ],
        "questions": [
            Q("What is the maximum transmitter power for US amateur stations on most bands?",
              "Wie hoch ist die maximale Senderleistung für US-Amateurstationen auf den meisten Bändern?",
              ["1500 watts PEP", "100 watts PEP", "500 watts PEP", "1000 watts PEP"],
              ["1500 Watt PEP", "100 Watt PEP", "500 Watt PEP", "1000 Watt PEP"]),
            Q("What is the maximum power on the 30 metre band (10.10 to 10.15 MHz)?",
              "Wie hoch ist die maximale Leistung auf dem 30-Meter-Band (10,10 bis 10,15 MHz)?",
              ["200 watts PEP", "1500 watts PEP", "50 watts PEP", "1000 watts PEP"],
              ["200 Watt PEP", "1500 Watt PEP", "50 Watt PEP", "1000 Watt PEP"]),
            Q("In which language must you identify your station on phone?",
              "In welcher Sprache musst du dich in Telefonie identifizieren?",
              ["English", "Spanish", "The language of the other station", "Any language you like"],
              ["Englisch", "Spanisch", "In der Sprache der Gegenstation", "In einer beliebigen Sprache"]),
            Q("How many questions does the General exam (Element 3) have, and how many must you answer correctly?",
              "Wie viele Fragen hat die General-Prüfung (Element 3), und wie viele musst du richtig beantworten?",
              ["35 questions, 26 correct", "35 questions, 35 correct", "50 questions, 37 correct", "25 questions, 20 correct"],
              ["35 Fragen, 26 richtig", "35 Fragen, 35 richtig", "50 Fragen, 37 richtig", "25 Fragen, 20 richtig"]),
            Q("Which 20 metre frequency may a General class operator use on phone?",
              "Welche Frequenz im 20-Meter-Band darf ein General-Funkamateur in Telefonie nutzen?",
              ["14.250 MHz", "14.180 MHz", "14.100 MHz", "14.010 MHz"],
              ["14,250 MHz", "14,180 MHz", "14,100 MHz", "14,010 MHz"]),
            Q("An Amateur Extra lets a General licensee operate the Extra's station. Whose privileges apply?",
              "Ein Amateur Extra lässt einen General-Inhaber an seiner Station funken. Welche Rechte gelten?",
              ["The General's, because privileges follow the control operator's class",
               "The Extra's, because it is the Extra's station",
               "The Extra's, but only on HF",
               "None, only the licensee may transmit"],
              ["Die des General, weil sich die Rechte nach der Klasse des Control Operators richten",
               "Die des Extra, weil es dessen Station ist",
               "Die des Extra, aber nur auf Kurzwelle",
               "Keine, nur der Lizenzinhaber darf senden"]),
            Q("What must be true when a third party takes part in a contact from your station?",
              "Was muss gelten, wenn ein Dritter von deiner Station aus an einer Verbindung teilnimmt?",
              ["The control operator is present and continuously supervises",
               "The third party holds a commercial radio licence",
               "The contact is shorter than 10 minutes",
               "The contact is on 2 metres only"],
              ["Der Control Operator ist anwesend und beaufsichtigt ständig",
               "Der Dritte besitzt eine gewerbliche Funklizenz",
               "Die Verbindung dauert weniger als 10 Minuten",
               "Die Verbindung findet nur auf 2 Metern statt"]),
            Q("About how long is a half-wave dipole for 7.1 MHz (40 metres)?",
              "Wie lang ist ein Halbwellendipol für 7,1 MHz (40 Meter) ungefähr?",
              ["About 20 metres", "About 10 metres", "About 40 metres", "About 5 metres"],
              ["Etwa 20 Meter", "Etwa 10 Meter", "Etwa 40 Meter", "Etwa 5 Meter"]),
            Q("Which band usually supports long-distance contacts in full daylight?",
              "Welches Band trägt tagsüber meist über große Entfernungen?",
              ["20 metres", "160 metres", "80 metres", "2 metres"],
              ["20 Meter", "160 Meter", "80 Meter", "2 Meter"]),
            Q("When may a new General licensee start using General privileges?",
              "Wann darf ein neuer General-Inhaber die General-Rechte nutzen?",
              ["When the upgrade appears in the FCC licence database",
               "Right after passing the exam, before any record",
               "After 30 days of waiting",
               "Only after a club sends a letter"],
              ["Sobald der Aufstieg in der FCC-Lizenzdatenbank steht",
               "Sofort nach bestandener Prüfung, noch vor dem Eintrag",
               "Nach 30 Tagen Wartezeit",
               "Erst nach einem Brief vom Club"]),
        ],
        "pass": 7,
    }

    extra = {
        "class": L("Amateur Extra", "Amateur Extra"),
        "licence": L("Amateur Extra class", "Amateur-Extra-Klasse"),
        "lessons": [
            _lesson(
                "All privileges",
                "Alle Rechte",
                "Amateur Extra is the top US class. It has every amateur privilege on every amateur band. The reserved segments include 3.500 to 3.525 and 3.600 to 3.800 MHz, 7.000 to 7.025 and 7.125 to 7.175 MHz, 14.000 to 14.025 and 14.150 to 14.225 MHz, and 21.000 to 21.025 and 21.200 to 21.275 MHz. The power limit stays at 1500 watts PEP.",
                "Amateur Extra ist die höchste US-Klasse. Sie hat alle Amateurfunkrechte auf allen Amateurfunkbändern. Vorbehalten sind unter anderem 3,500 bis 3,525 und 3,600 bis 3,800 MHz, 7,000 bis 7,025 und 7,125 bis 7,175 MHz, 14,000 bis 14,025 und 14,150 bis 14,225 MHz sowie 21,000 bis 21,025 und 21,200 bis 21,275 MHz. Die Leistungsgrenze bleibt bei 1500 Watt PEP."),
            _lesson(
                "The Element 4 exam",
                "Die Prüfung Element 4",
                "Element 4 has 50 questions and you need 37 correct. It goes deeper into electronics, antennas, propagation, station design and FCC rules, so plan real study time. Exams are given by a team of at least three volunteer examiners under a VEC. Element 4 must be given by examiners who hold Amateur Extra themselves.",
                "Element 4 hat 50 Fragen, und du brauchst 37 richtige Antworten. Die Prüfung geht tiefer in Elektronik, Antennen, Wellenausbreitung, Stationsaufbau und FCC-Regeln, plane also echte Lernzeit ein. Geprüft wird von einem Team aus mindestens drei ehrenamtlichen Prüfern unter einem VEC. Element 4 müssen Prüfer abnehmen, die selbst Amateur Extra besitzen."),
            _lesson(
                "Short callsigns",
                "Kurze Rufzeichen",
                "Amateur Extra can ask for vanity callsigns from Group A: one-letter prefix with two-letter suffix (like W1AW), two-letter prefix with one-letter suffix, and two-by-two calls that start with A. A licensee may pick from their own group or a lower one. A deceased licensee's callsign is held back for two years, unless a previous holder or a family member asks for it.",
                "Amateur Extra kann Wunschrufzeichen aus Gruppe A beantragen: ein Buchstabe als Präfix mit zwei Buchstaben im Suffix (wie W1AW), zwei Buchstaben Präfix mit einem Buchstaben Suffix sowie Zwei-mal-zwei-Rufzeichen, die mit A beginnen. Man darf aus der eigenen oder einer niedrigeren Gruppe wählen. Das Rufzeichen eines Verstorbenen bleibt zwei Jahre gesperrt, außer ein früherer Inhaber oder ein Familienmitglied beantragt es."),
            _lesson(
                "Responsibility and forbidden traffic",
                "Verantwortung und verbotener Verkehr",
                "The licensee is responsible for proper operation of the station. If another amateur is control operator, both are equally responsible. You may not transmit for pay, send music, use obscene language, broadcast, or send codes meant to hide the meaning of a message. Brief test transmissions, Morse practice and bulletins are fine, and so are emergency communications.",
                "Der Lizenzinhaber ist für den ordnungsgemäßen Betrieb der Station verantwortlich. Ist ein anderer Funkamateur Control Operator, sind beide gleichermaßen verantwortlich. Verboten sind Sendungen gegen Bezahlung, Musik, obszöne Sprache, Rundfunk und Codes, die den Inhalt einer Nachricht verschleiern sollen. Kurze Testsendungen, Morseübungen und Bulletins sind in Ordnung, ebenso Notfunkverkehr in echten Notlagen."),
        ],
        "questions": [
            Q("How many questions does the Amateur Extra exam (Element 4) have, and how many must you answer correctly?",
              "Wie viele Fragen hat die Amateur-Extra-Prüfung (Element 4), und wie viele musst du richtig beantworten?",
              ["50 questions, 37 correct", "35 questions, 26 correct", "50 questions, 50 correct", "100 questions, 75 correct"],
              ["50 Fragen, 37 richtig", "35 Fragen, 26 richtig", "50 Fragen, 50 richtig", "100 Fragen, 75 richtig"]),
            Q("Which 40 metre frequency is reserved for Amateur Extra?",
              "Welche Frequenz im 40-Meter-Band ist Amateur Extra vorbehalten?",
              ["7.150 MHz", "7.050 MHz", "7.200 MHz", "7.280 MHz"],
              ["7,150 MHz", "7,050 MHz", "7,200 MHz", "7,280 MHz"]),
            Q("Which vanity callsign format is available only to Amateur Extra?",
              "Welches Format eines Wunschrufzeichens steht nur Amateur Extra offen?",
              ["One-letter prefix and two-letter suffix, such as W1AW",
               "One-letter prefix and three-letter suffix, such as K1ABC",
               "Two-letter prefix and three-letter suffix, such as KD2ABC",
               "Any format with a K prefix"],
              ["Ein Buchstabe Präfix und zwei Buchstaben Suffix, wie W1AW",
               "Ein Buchstabe Präfix und drei Buchstaben Suffix, wie K1ABC",
               "Zwei Buchstaben Präfix und drei Buchstaben Suffix, wie KD2ABC",
               "Jedes Format mit K als Präfix"]),
            Q("Who must give the Element 4 exam?",
              "Wer muss die Prüfung Element 4 abnehmen?",
              ["A team of at least three volunteer examiners who hold Amateur Extra",
               "A single FCC officer",
               "Two examiners of any class",
               "The local ham club president"],
              ["Ein Team aus mindestens drei ehrenamtlichen Prüfern mit Amateur Extra",
               "Ein einzelner FCC-Beamter",
               "Zwei Prüfer beliebiger Klasse",
               "Der Vorsitzende des örtlichen Clubs"]),
            Q("For how long is a deceased licensee's callsign normally unavailable to others?",
              "Wie lange ist das Rufzeichen eines Verstorbenen normalerweise für andere gesperrt?",
              ["Two years", "Six months", "Ten years", "It is reissued the next day"],
              ["Zwei Jahre", "Sechs Monate", "Zehn Jahre", "Es wird am nächsten Tag neu vergeben"]),
            Q("A station licensee lets another amateur act as control operator. Who is responsible for proper operation?",
              "Ein Lizenzinhaber lässt einen anderen Funkamateur als Control Operator arbeiten. Wer ist für den ordnungsgemäßen Betrieb verantwortlich?",
              ["Both, equally", "Only the licensee", "Only the control operator", "The FCC"],
              ["Beide gleichermaßen", "Nur der Lizenzinhaber", "Nur der Control Operator", "Die FCC"]),
            Q("Which transmission is prohibited on amateur frequencies?",
              "Welche Sendung ist auf Amateurfunkfrequenzen verboten?",
              ["A message in a code meant to hide its meaning",
               "Using Q-codes and abbreviations",
               "A brief transmission to adjust the station",
               "A contact with a station in another country"],
              ["Eine Nachricht in einem Code, der ihren Inhalt verschleiern soll",
               "Die Verwendung von Q-Gruppen und Abkürzungen",
               "Eine kurze Sendung zum Einstellen der Station",
               "Eine Verbindung mit einer Station in einem anderen Land"]),
            Q("At what frequency does a circuit with 10 microhenries and 100 picofarads resonate?",
              "Bei welcher Frequenz schwingt ein Kreis mit 10 Mikrohenry und 100 Pikofarad in Resonanz?",
              ["About 5 MHz", "About 50 MHz", "About 0.5 MHz", "About 16 MHz"],
              ["Etwa 5 MHz", "Etwa 50 MHz", "Etwa 0,5 MHz", "Etwa 16 MHz"]),
            Q("By about how much does a 6 dB increase raise the power?",
              "Um etwa welchen Faktor erhöht eine Zunahme um 6 dB die Leistung?",
              ["Four times", "Twice", "Six times", "Ten times"],
              ["Vierfach", "Doppelt", "Sechsfach", "Zehnfach"]),
            Q("Does Amateur Extra allow more than 1500 watts PEP on the HF bands?",
              "Erlaubt Amateur Extra auf den Kurzwellenbändern mehr als 1500 Watt PEP?",
              ["No, 1500 watts PEP is the limit for everyone", "Yes, up to 5000 watts", "Yes, but only at night", "Yes, with a special permit"],
              ["Nein, 1500 Watt PEP gelten für alle als Grenze", "Ja, bis zu 5000 Watt", "Ja, aber nur nachts", "Ja, mit einer Sondergenehmigung"]),
        ],
        "pass": 7,
    }
    return [general, extra]


# ----------------------------------------------------------------------------------------
# United Kingdom
# ----------------------------------------------------------------------------------------
def uk_levels():
    inter = {
        "class": L("Intermediate", "Intermediate"),
        "licence": L("Intermediate licence", "Intermediate-Lizenz"),
        "lessons": [
            _lesson(
                "What Intermediate adds",
                "Was Intermediate dazu bringt",
                "The Intermediate licence is the middle step of the UK ladder and raises your power limit to 100 watts PEP (Foundation: 25 watts). You take the exam after Foundation: 46 multiple-choice questions in 90 minutes, each with four answers. Since February 2024, all licensees may also control a station remotely over the internet.",
                "Die Intermediate-Lizenz ist die mittlere Stufe der britischen Leiter und hebt deine Leistungsgrenze auf 100 Watt PEP an (Foundation: 25 Watt). Die Prüfung legst du nach Foundation ab: 46 Multiple-Choice-Fragen in 90 Minuten, jeweils mit vier Antworten. Seit Februar 2024 dürfen außerdem ausnahmslos alle Lizenzinhaber eine Station per Internet fernsteuern."),
            _lesson(
                "Your Intermediate callsign",
                "Dein Intermediate-Rufzeichen",
                "New Intermediate callsigns start with M8 or M9, followed by three letters. Older Intermediate callsigns began with a 2 and keep their regional locator. For newer callsigns, the locator is optional. After the slash you may add any suffix, for example /P for portable or /M for mobile, as long as your station stays identifiable.",
                "Neue Intermediate-Rufzeichen beginnen mit M8 oder M9, gefolgt von drei Buchstaben. Ältere Intermediate-Rufzeichen begannen mit einer 2 und behalten ihren Regionalcode. Bei neueren Rufzeichen ist dieser Regionalcode freiwillig. Nach dem Schrägstrich darfst du einen beliebigen Zusatz anhängen, zum Beispiel /P für portabel oder /M für mobil, solange deine Station erkennbar bleibt."),
            _lesson(
                "Guests and licence upkeep",
                "Gäste und Pflege der Lizenz",
                "Anyone may use your station, as long as you supervise them directly and physically. Your licence is for life, provided you revalidate it every five years and keep your details up to date in Ofcom's online licensing system. Applying online costs nothing. If you neglect your details, Ofcom may propose to revoke the licence.",
                "Jeder darf deine Station benutzen, solange du ihn direkt und persönlich beaufsichtigst. Deine Lizenz gilt lebenslang, wenn du sie alle fünf Jahre bestätigst und deine Angaben im Online-Lizenzsystem von Ofcom aktuell hältst. Die Online-Beantragung kostet nichts. Wer seine Angaben vernachlässigt, muss damit rechnen, dass Ofcom den Widerruf der Lizenz vorschlägt."),
            _lesson(
                "Rules that stay the same",
                "Regeln, die gleich bleiben",
                "Amateur radio stays strictly non-commercial. You may not send messages for general reception, except initial CQ calls or transmissions to groups of three or more amateurs. Your equipment must not cause undue interference to other users, even home-built gear. Keep in mind that 100 watts is 20 dBW: every tenfold power step adds 10 dB.",
                "Amateurfunk bleibt streng nichtkommerziell. Du darfst keine Nachrichten zum allgemeinen Empfang senden, außer erste CQ-Rufe oder Sendungen an Gruppen von drei oder mehr Funkamateuren. Deine Geräte dürfen andere Funknutzer nicht unzumutbar stören, auch nicht mit selbstgebauter Technik. Merke: 100 Watt entsprechen 20 dBW, jeder Sprung um den Faktor zehn bringt 10 dB."),
        ],
        "questions": [
            Q("What is the maximum power for an Intermediate licence?",
              "Wie hoch ist die Höchstleistung bei der Intermediate-Lizenz?",
              ["100 watts PEP", "25 watts PEP", "400 watts PEP", "10 watts PEP"],
              ["100 Watt PEP", "25 Watt PEP", "400 Watt PEP", "10 Watt PEP"]),
            Q("How many questions does the Intermediate exam have?",
              "Wie viele Fragen hat die Intermediate-Prüfung?",
              ["46 multiple-choice questions", "26 multiple-choice questions", "58 multiple-choice questions", "100 multiple-choice questions"],
              ["46 Multiple-Choice-Fragen", "26 Multiple-Choice-Fragen", "58 Multiple-Choice-Fragen", "100 Multiple-Choice-Fragen"]),
            Q("What must you pass before you may sit the Intermediate exam?",
              "Was musst du bestehen, bevor du die Intermediate-Prüfung ablegen darfst?",
              ["The Foundation exam", "The Full exam", "A Morse test", "A driving test"],
              ["Die Foundation-Prüfung", "Die Full-Prüfung", "Eine Morseprüfung", "Eine Fahrprüfung"]),
            Q("Which prefixes do new Intermediate callsigns start with?",
              "Mit welchen Präfixen beginnen neue Intermediate-Rufzeichen?",
              ["M8 or M9", "M3 or M6", "M0 or M1", "G4 or G8"],
              ["M8 oder M9", "M3 oder M6", "M0 oder M1", "G4 oder G8"]),
            Q("What does the suffix /M show after your callsign?",
              "Was zeigt der Zusatz /M hinter deinem Rufzeichen an?",
              ["You are operating mobile", "You are at sea", "You are a member of a club", "You are using low power"],
              ["Du funkst mobil", "Du bist auf See", "Du bist Clubmitglied", "Du sendest mit geringer Leistung"]),
            Q("How often must you revalidate your Ofcom amateur licence?",
              "Wie oft musst du deine Amateurfunklizenz bei Ofcom bestätigen?",
              ["Every five years", "Every year", "Every 20 years", "Never"],
              ["Alle fünf Jahre", "Jedes Jahr", "Alle 20 Jahre", "Nie"]),
            Q("Under what condition may a visitor use your station?",
              "Unter welcher Bedingung darf ein Besucher deine Station benutzen?",
              ["You supervise them directly and physically", "They own a scanner", "They pay a small fee", "They are over 60"],
              ["Du beaufsichtigst ihn direkt und persönlich", "Er besitzt einen Scanner", "Er zahlt eine kleine Gebühr", "Er ist über 60"]),
            Q("Which transmission to the general public is allowed?",
              "Welche Sendung an die Allgemeinheit ist erlaubt?",
              ["An initial CQ call", "A music broadcast", "An advert for your shop", "A weather forecast for listeners"],
              ["Ein erster CQ-Ruf", "Eine Musiksendung", "Eine Werbung für dein Geschäft", "Ein Wetterbericht für Zuhörer"]),
            Q("How many decibels higher is 100 watts than 10 watts?",
              "Um wie viele Dezibel ist 100 Watt größer als 10 Watt?",
              ["10 dB", "3 dB", "20 dB", "100 dB"],
              ["10 dB", "3 dB", "20 dB", "100 dB"]),
            Q("About how long is the wavelength at 7.1 MHz?",
              "Wie lang ist die Wellenlänge bei 7,1 MHz ungefähr?",
              ["About 42 metres", "About 4 metres", "About 420 metres", "About 10 metres"],
              ["Etwa 42 Meter", "Etwa 4 Meter", "Etwa 420 Meter", "Etwa 10 Meter"]),
        ],
        "pass": 7,
    }

    full = {
        "class": L("Full", "Full"),
        "licence": L("Full licence", "Full-Lizenz"),
        "lessons": [
            _lesson(
                "What Full adds",
                "Was Full dazu bringt",
                "The Full licence has the highest power limits: 400 watts PEP on most bands and up to 1000 watts (30 dBW) on primary bands. You take the exam after Intermediate: 58 multiple-choice questions in two hours. A pass brings a HAREC certificate. Only Full licensees can seek to operate overseas under the CEPT rules.",
                "Die Full-Lizenz hat die höchsten Leistungsgrenzen: 400 Watt PEP auf den meisten Bändern und bis zu 1000 Watt (30 dBW) auf Primärbändern. Die Prüfung legst du nach Intermediate ab: 58 Multiple-Choice-Fragen in zwei Stunden. Mit dem Bestehen erhältst du ein HAREC-Zertifikat. Nur Full-Lizenzinhaber können eine Genehmigung für den Funkbetrieb im Ausland nach den CEPT-Regeln beantragen."),
            _lesson(
                "Callsigns and operating abroad",
                "Rufzeichen und Funkbetrieb im Ausland",
                "Full callsigns start with M0, M1 or M5, or with G and a digit, then normally three letters. Regional locators are optional, and England now has its own locator, E. Under CEPT you may operate in other participating countries for a short stay, usually up to three months, and you put the country prefix in front of your callsign.",
                "Full-Rufzeichen beginnen mit M0, M1 oder M5 oder mit G und einer Ziffer, danach normalerweise drei Buchstaben. Regionalcodes sind freiwillig, und England hat mit E jetzt einen eigenen. Nach CEPT darfst du in anderen teilnehmenden Ländern kurzzeitig funken, meist bis zu drei Monate, und stellst deinem Rufzeichen das Länderpräfix voran."),
            _lesson(
                "Notices of Variation",
                "Notices of Variation",
                "Some activities need a Notice of Variation (NoV) from Ofcom: a special event station, a special contest callsign, beacons or repeaters above 25 watts ERP, and extra frequency bands such as 70.5 to 71.5 MHz. Under a Full (Club) licence, any Full licensee can supervise guests using the club station. Ofcom's online licensing system handles the paperwork.",
                "Manche Aktivitäten brauchen eine Notice of Variation (NoV) von Ofcom: eine Sonderstation, ein besonderes Contest-Rufzeichen, Baken oder Relaisstellen über 25 Watt ERP und zusätzliche Frequenzbereiche wie 70,5 bis 71,5 MHz. Bei einer Full-(Club-)Lizenz kann jeder Full-Inhaber Gäste an der Klubstation beaufsichtigen. Den Papierkram erledigst du über das Online-Lizenzsystem von Ofcom."),
            _lesson(
                "Duties of a Full licensee",
                "Pflichten eines Full-Inhabers",
                "You must keep your licence details correct and revalidate every five years. If you do not, Ofcom may propose to revoke the licence. Your traffic stays non-commercial. You send messages to other amateurs, not to the general public, except CQ calls and transmissions to groups of three or more. A Full licence gives power and freedom, and more responsibility.",
                "Du musst deine Lizenzdaten korrekt halten und sie alle fünf Jahre bestätigen. Tust du das nicht, kann Ofcom den Widerruf der Lizenz vorschlagen. Dein Funkverkehr bleibt nichtkommerziell. Du sendest Nachrichten an andere Funkamateure, nicht an die Allgemeinheit, außer CQ-Rufe und Sendungen an Gruppen von drei oder mehr. Die Full-Lizenz bringt Leistung und Freiheit, aber auch mehr Verantwortung."),
        ],
        "questions": [
            Q("What is the highest power a Full licence allows on primary bands?",
              "Wie hoch ist die höchste Leistung, die die Full-Lizenz auf Primärbändern erlaubt?",
              ["1000 watts PEP", "400 watts PEP", "100 watts PEP", "2000 watts PEP"],
              ["1000 Watt PEP", "400 Watt PEP", "100 Watt PEP", "2000 Watt PEP"]),
            Q("How many questions does the Full exam have?",
              "Wie viele Fragen hat die Full-Prüfung?",
              ["58 multiple-choice questions", "46 multiple-choice questions", "26 multiple-choice questions", "20 multiple-choice questions"],
              ["58 Multiple-Choice-Fragen", "46 Multiple-Choice-Fragen", "26 Multiple-Choice-Fragen", "20 Multiple-Choice-Fragen"]),
            Q("Which exam must you pass before the Full exam?",
              "Welche Prüfung musst du vor der Full-Prüfung bestehen?",
              ["The Intermediate exam", "A Morse exam", "A computer exam", "No other exam"],
              ["Die Intermediate-Prüfung", "Eine Morseprüfung", "Eine Computerprüfung", "Keine andere Prüfung"]),
            Q("Which callsign format belongs to a Full licence?",
              "Welches Rufzeichenformat gehört zu einer Full-Lizenz?",
              ["M0ABC", "M3ABC", "M6ABC", "M8ABC"],
              ["M0ABC", "M3ABC", "M6ABC", "M8ABC"]),
            Q("Which licence level can seek to operate overseas under CEPT?",
              "Welche Lizenzstufe kann den Funkbetrieb im Ausland nach CEPT beantragen?",
              ["Full only", "Foundation only", "Foundation and Intermediate", "All three levels"],
              ["Nur Full", "Nur Foundation", "Foundation und Intermediate", "Alle drei Stufen"]),
            Q("For a short stay under CEPT, how long can you usually operate in another country?",
              "Wie lange darfst du bei einem Kurzaufenthalt nach CEPT in einem anderen Land meist funken?",
              ["Up to three months", "One week", "Up to five years", "Only one day"],
              ["Bis zu drei Monate", "Eine Woche", "Bis zu fünf Jahre", "Nur einen Tag"]),
            Q("What do you need to run a special event station?",
              "Was brauchst du, um eine Sonderstation zu betreiben?",
              ["A Notice of Variation", "A second exam", "A club of 50 members", "Nothing at all"],
              ["Eine Notice of Variation", "Eine zweite Prüfung", "Einen Club mit 50 Mitgliedern", "Gar nichts"]),
            Q("Under a Full (Club) licence, who may supervise guests using the club station?",
              "Wer darf bei einer Full-(Club-)Lizenz Gäste an der Klubstation beaufsichtigen?",
              ["Any Full licensee", "Only the club chairperson", "Only Foundation holders", "Nobody, guests may not transmit"],
              ["Jeder Full-Inhaber", "Nur der Clubvorsitzende", "Nur Foundation-Inhaber", "Niemand, Gäste dürfen nicht senden"]),
            Q("How many dBW is 1000 watts?",
              "Wie viele dBW entsprechen 1000 Watt?",
              ["30 dBW", "10 dBW", "20 dBW", "40 dBW"],
              ["30 dBW", "10 dBW", "20 dBW", "40 dBW"]),
            Q("What may Ofcom propose if a licensee does not keep their details up to date?",
              "Was kann Ofcom vorschlagen, wenn ein Lizenzinhaber seine Angaben nicht aktuell hält?",
              ["To revoke the licence", "To double the power limit", "To change the callsign to G0", "To add a second exam"],
              ["Die Lizenz zu widerrufen", "Die Leistungsgrenze zu verdoppeln", "Das Rufzeichen in G0 zu ändern", "Eine zweite Prüfung anzusetzen"]),
        ],
        "pass": 7,
    }
    return [inter, full]
