# -*- coding: utf-8 -*-
"""UI strings added with settings, avatar editor, badges, statistics and library. (en, de)."""

UI_MORE = {
    "settings.title": ("Settings", "Einstellungen"),
    "settings.profile": ("Profile", "Profil"),
    "settings.stats": ("Statistics", "Statistik"),
    "settings.badges": ("Badges", "Abzeichen"),
    "settings.language": ("Language", "Sprache"),
    "settings.game": ("Game", "Spiel"),
    "settings.about": ("About and licences", "Info und Lizenzen"),
    "settings.edit_profile": ("Edit avatar, name and country", "Avatar, Name und Land ändern"),
    "settings.since": ("Playing since %s", "Dabei seit %s"),
    "settings.lang_note": ("Translations other than English and German were made with AI and are not yet reviewed by native speakers.",
                           "Übersetzungen außer Englisch und Deutsch wurden mit KI erstellt und noch nicht von Muttersprachlern geprüft."),
    "settings.lang_content": ("Lessons and questions exist in English and German. In other languages you see the English lessons.",
                              "Lektionen und Fragen gibt es auf Englisch und Deutsch. In anderen Sprachen siehst du die englischen Lektionen."),
    "settings.sound": ("Sound", "Ton"),
    "settings.reset_text": ("Start a new game. All progress, your callsign and your avatar are deleted.",
                            "Neues Spiel starten. Aller Fortschritt, dein Rufzeichen und dein Avatar werden gelöscht."),
    "settings.library": ("Open the library", "Bibliothek öffnen"),
    "stat.level": ("Level", "Stufe"),
    "stat.parts": ("Shack parts earned", "Shack-Teile verdient"),
    "stat.lessons": ("Lessons read", "Lektionen gelesen"),
    "stat.answers": ("Quiz answers", "Quiz-Antworten"),
    "stat.accuracy": ("Correct answers", "Richtige Antworten"),
    "stat.quizzes": ("Quizzes passed", "Quizze bestanden"),
    "stat.qso": ("QSO steps done", "QSO-Schritte geschafft"),
    "stat.morse": ("Morse levels passed", "Morse-Stufen bestanden"),
    "stat.wpm": ("Morse speed", "Morse-Tempo"),
    "stat.badges": ("Badges earned", "Abzeichen verdient"),
    "badge.first_part.t": ("First part", "Erstes Teil"),
    "badge.first_part.d": ("Earn your first shack part.", "Verdiene dein erstes Shack-Teil."),
    "badge.full_shack.t": ("Full shack", "Volles Shack"),
    "badge.full_shack.d": ("Own all 8 shack parts.", "Besitze alle 8 Shack-Teile."),
    "badge.rules.t": ("Rule keeper", "Regelkenner"),
    "badge.rules.d": ("Pass the rules quiz of your country.", "Bestehe das Regel-Quiz deines Landes."),
    "badge.callsign.t": ("On the air", "Auf Sendung"),
    "badge.callsign.d": ("Claim your callsign.", "Sichere dir dein Rufzeichen."),
    "badge.qso.t": ("First contact", "Erster Kontakt"),
    "badge.qso.d": ("Finish your first QSO.", "Schließe dein erstes QSO ab."),
    "badge.morse3.t": ("Dit and dah", "Dit und Dah"),
    "badge.morse3.d": ("Pass 3 Morse levels.", "Bestehe 3 Morse-Stufen."),
    "badge.morse10.t": ("Morse master", "Morsemeister"),
    "badge.morse10.d": ("Pass all 10 Morse levels.", "Bestehe alle 10 Morse-Stufen."),
    "badge.level2.t": ("Level 2", "Stufe 2"),
    "badge.level2.d": ("Reach the second licence class.", "Erreiche die zweite Lizenzklasse."),
    "badge.level3.t": ("Level 3", "Stufe 3"),
    "badge.level3.d": ("Reach the third licence class.", "Erreiche die dritte Lizenzklasse."),
    "badge.reader.t": ("Bookworm", "Bücherwurm"),
    "badge.reader.d": ("Read 25 lessons.", "Lies 25 Lektionen."),
    "badge.quiz50.t": ("Quiz fan", "Quiz-Fan"),
    "badge.quiz50.d": ("Answer 50 questions correctly.", "Beantworte 50 Fragen richtig."),
    "badge.perfect.t": ("Perfect score", "Volle Punktzahl"),
    "badge.perfect.d": ("Finish a quiz without a mistake.", "Beende ein Quiz ohne Fehler."),
    "avatar.skin": ("Skin", "Haut"),
    "avatar.age": ("Age", "Alter"),
    "avatar.gender": ("Gender", "Geschlecht"),
    "avatar.hair": ("Hair style", "Frisur"),
    "avatar.haircol": ("Hair colour", "Haarfarbe"),
    "avatar.beard": ("Beard", "Bart"),
    "avatar.glasses": ("Glasses", "Brille"),
    "avatar.hat": ("Headwear", "Kopfbedeckung"),
    "avatar.shirt": ("Shirt", "Shirt"),
    "avatar.headset": ("Headset", "Headset"),
    "avatar.random": ("Surprise me", "Überrasch mich"),
    "avatar.age0": ("Young", "Jung"),
    "avatar.age1": ("Adult", "Erwachsen"),
    "avatar.age2": ("Senior", "Senior"),
    "avatar.gender0": ("Female", "Weiblich"),
    "avatar.gender1": ("Male", "Männlich"),
    "avatar.gender2": ("Neutral", "Neutral"),
    "avatar.on": ("On", "An"),
    "avatar.off": ("Off", "Aus"),
    "hub.library": ("Library", "Bibliothek"),
    "library.title": ("Library", "Bibliothek"),
    "library.sub": ("Look up ham radio terms: %d entries", "Funk-Begriffe nachschlagen: %d Einträge"),
    "library.search": ("Search a term", "Begriff suchen"),
    "library.all": ("All topics", "Alle Themen"),
    "library.empty": ("Nothing found.", "Nichts gefunden."),
    "library.see_also": ("See also", "Siehe auch"),
    "library.level1": ("Beginner", "Einsteiger"),
    "library.level2": ("Intermediate", "Fortgeschritten"),
    "library.level3": ("Advanced", "Experte"),
    "cat.modes": ("Modes", "Betriebsarten"),
    "cat.qcodes": ("Q-codes", "Q-Gruppen"),
    "cat.operating": ("Operating", "Funkbetrieb"),
    "cat.equipment": ("Equipment", "Geräte"),
    "cat.antennas": ("Antennas and lines", "Antennen und Leitungen"),
    "cat.propagation": ("Propagation", "Ausbreitung"),
    "cat.electronics": ("Electronics", "Elektronik"),
    "cat.rules": ("Rules and safety", "Regeln und Sicherheit"),
    "cat.learning": ("Learning", "Lernen"),
}
